# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamdescription', models.CharField(max_length=200)),
                ('teamtype', models.CharField(choices=[('Research', 'Research'), ('Development', 'Development')], default='Development', max_length=11)),
            ],
        ),
    ]
