# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('TeamManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamdescription', models.CharField(max_length=200)),
                ('teamtype', models.CharField(choices=[('Research', 'Research'), ('Development', 'Development')], default='Development', max_length=11)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
